const routes = {
    home: '/',
    women: '/?view=women',
    men: '/?view=men',
    kids: '/?view=kids',
    trademark: '/thuong-hieu',
    sale: '/special-deal',
    newIn: '/collections/new-arrival',
    login: '/tai-khoan/dang-nhap',
    register: '/tai-khoan/dang-ky',
    product: '/san-pham/:product',
    cart: '/gio-hang',
    checkingOrder: '/kiem-tra-don-hang',
    payment: '/thanh-toan',
    account: '/tai-khoan',
    order: '/tai-khoan/don-hang',
    changePassword: '/tai-khoan/doi-mat-khau',
    address: '/tai-khoan/dia-chi',
    policy: '/pages/chinh-sach-bao-mat',
};
export default routes;
